### PR TITLE
test(schema): add (failing) tests when schema is set

### PR DESCRIPTION
**Pull request by BrainCrumbz**
This PR tries to be a starting point to work on issue #14 . The very first step has been to add failing tests. Will wait for some feedback from maintainers before moving forward.

### CODE REVIEW

**Comment by yukozh** [comment]
Hi, I've sent you an invitation to Pomelo Foundation, thanks for your contribution.

**Comment by BrainCrumbz** [comment]
You're welcome. @Kagamine it seems like AppVeyor build is failing for reasons unrelated to current code changes: 

> MSBUILD : error MSB1001: Unknown switch.
Switch: --quiet

Travis builds fail for unrelated reasons as well:

> $ ./build.sh
/home/travis/.travis/job_stages: line 57: ./build.sh: Permission denied

For what it matters, on our local windows dev machine, all Sql Server tests pass in VS.

**Comment by BrainCrumbz** [comment]
Do you plan to release a newer 1.x package version? Before hitting this schema issue, we were working with 1.1.0.

**Comment by yukozh** [comment]
It seems that I have no time to do that, but could you give me your myget username, I will authorize you to publish packages.

**Comment by BrainCrumbz** [comment]
Hi there. That's ok, provided the process is straightforward. Our team myget account is *BrainCrumbz*. What are the instructions for build/deploy/publish specific for this project? 

Thanks

**Comment by yukozh** [comment]
1. Fixes the CI build scripts, you can refer to other projects in Pomelo Foundation, if you want to make a 1.1.x release, please create a new branch.
2. Sign in myget, click the pomelo foundation, then go into the build service, find the lolita project to build.
3. After building finished, click the down arrow, and find the latest package, click push to nuget.

**Comment by BrainCrumbz** [comment]
Uhm, let's move this part into a proper issue, #16

**Pull request merged**
